// MIRROR of src/data/snapCards.ts — keep in sync.
import type { SnapCardDef } from "./types.ts";

/**
 * SNAP card pool. Each card has ONLY cost, power, and one ability sentence.
 * `abilityId` maps to a pure handler in /lib/game/snap/snapAbilities.ts.
 * Image paths reuse the existing /public/cards/<slug>.png art slots; the UI
 * renders a gradient/initials placeholder when art is missing.
 *
 * Balance lives entirely here + the ability registry, so cards are easy to
 * retune. Keep this file in sync with the server mirror under
 * supabase/functions/_shared/snap/snapCards.ts.
 */
export const SNAP_CARDS: SnapCardDef[] = [
  {
    id: "pepe_the_frog",
    name: "Pepe the Frog",
    slug: "pepe-the-frog",
    rarity: "Legendary",
    cost: 3,
    power: 3,
    abilityText: "On Reveal: Give your other cards here +1 Power.",
    abilityType: "on_reveal",
    abilityId: "buffOthersHere",
    tags: ["Support", "Meme", "On Reveal"],
    imagePath: "/cards/pepe-the-frog.png",
    flavor: "Feels good, man. Lifts the whole lane's vibe.",
    levels: [
      { level: 1, description: "Give your other cards here +1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 3, abilityBonus: 1, description: "Buff increased to +2 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Buff +3 Power." },
    ],
  },
  {
    id: "dogwifhat",
    name: "Dogwifhat",
    slug: "dogwifhat",
    rarity: "Epic",
    cost: 2,
    power: 3,
    abilityText: "If you are winning this location, this has +2 Power.",
    abilityType: "conditional",
    abilityId: "winningHereBonus",
    tags: ["Animal", "Hype", "Conditional"],
    imagePath: "/cards/dogwifhat.png",
    flavor: "Just a dog. With a hat. Wins harder when ahead.",
    levels: [
      { level: 1, description: "If winning here, +2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 3, abilityBonus: 1, description: "Bonus increased to +3 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Bonus +4 Power." },
    ],
  },
  {
    id: "mog_cat",
    name: "Mog Cat",
    slug: "mog-cat",
    rarity: "Epic",
    cost: 3,
    power: 5,
    abilityText: "On Reveal: If an enemy here has less Power, gain +2 Power.",
    abilityType: "on_reveal",
    abilityId: "bonusIfEnemyWeaker",
    tags: ["Cat", "On Reveal", "Scaling"],
    imagePath: "/cards/mog-cat.png",
    flavor: "Mogs everything in the room. Especially you.",
    levels: [
      { level: 1, description: "If an enemy here is weaker, +2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 3, abilityBonus: 1, description: "Bonus increased to +3 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 7)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Bonus +4 Power." },
    ],
  },
  {
    id: "popcat",
    name: "Popcat",
    slug: "popcat",
    rarity: "Rare",
    cost: 1,
    power: 1,
    abilityText: "On Reveal: Add a 1-Power Pop Token here if there is space.",
    abilityType: "on_reveal",
    abilityId: "spawnPopToken",
    tags: ["Cat", "Token", "On Reveal"],
    imagePath: "/cards/popcat.png",
    flavor: "Pop. Pop. Pop. Pop.",
    levels: [
      { level: 1, description: "Add a 1-Power Pop Token here." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 2)." },
      { level: 3, abilityBonus: 1, description: "Pop Token has 2 Power." },
      { level: 4, abilityBonus: 1, description: "Pop Token has 3 Power." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "peanut_the_squirrel",
    name: "Peanut the Squirrel",
    slug: "peanut-the-squirrel",
    rarity: "Rare",
    cost: 1,
    power: 2,
    abilityText: "On Reveal: Next turn, you have +1 Energy.",
    abilityType: "on_reveal",
    abilityId: "rampEnergy",
    tags: ["Animal", "Ramp", "On Reveal"],
    imagePath: "/cards/peanut-the-squirrel.png",
    flavor: "Gone too soon. Hoards energy like acorns.",
    levels: [
      { level: 1, description: "Next turn, +1 Energy." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 3, abilityBonus: 1, description: "Next turn, +2 Energy." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "moo_deng_hippo",
    name: "Moo Deng Hippo",
    slug: "moo-deng-hippo",
    rarity: "Epic",
    cost: 4,
    power: 7,
    abilityText: "Ongoing: This card's Power can't be reduced.",
    abilityType: "ongoing",
    abilityId: "ongoingCannotReducePower",
    tags: ["Animal", "Tank", "Ongoing"],
    imagePath: "/cards/moo-deng-hippo.png",
    flavor: "Slippery, bouncy, absolutely unbothered.",
    levels: [
      { level: 1, description: "Power can't be reduced." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 8)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 9)." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 10)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "tung_tung_tung_sahur",
    name: "Tung Tung Tung Sahur",
    slug: "tung-tung-tung-sahur",
    rarity: "Rare",
    cost: 3,
    power: 4,
    abilityText: "On Reveal: Disable the next enemy On Reveal here this turn.",
    abilityType: "on_reveal",
    abilityId: "disableEnemyOnReveal",
    tags: ["Control", "On Reveal"],
    imagePath: "/cards/tung-tung-tung-sahur.png",
    flavor: "Tung tung tung... sahur. You hear it at 3AM.",
    levels: [
      { level: 1, description: "Disable next enemy On Reveal here." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 4, abilityBonus: 1, description: "Disables enemy On Reveals all turn." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "gigachad",
    name: "GigaChad",
    slug: "gigachad",
    rarity: "Legendary",
    cost: 6,
    power: 12,
    abilityText: "If this is your only card here, +4 Power.",
    abilityType: "conditional",
    abilityId: "aloneHereBonus",
    tags: ["Finisher", "Conditional"],
    imagePath: "/cards/gigachad.png",
    flavor: "Yes. I have 12 Power. Thanks for asking.",
    levels: [
      { level: 1, description: "If alone here, +4 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 13)." },
      { level: 3, abilityBonus: 1, description: "Alone bonus increased to +5." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 14)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Alone bonus +6." },
    ],
  },
  {
    id: "ballerina_cappuccino",
    name: "Ballerina Cappuccino",
    slug: "ballerina-cappuccino",
    rarity: "Epic",
    cost: 2,
    power: 2,
    abilityText: "On Reveal: Move this to another location and gain +2 Power.",
    abilityType: "on_reveal",
    abilityId: "moveSelfGainPower",
    tags: ["Move", "Brainrot", "On Reveal"],
    imagePath: "/cards/ballerina-cappuccino.png",
    flavor: "Pirouettes through the orderbook. Espresso-fueled.",
    levels: [
      { level: 1, description: "Move self, gain +2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 3, abilityBonus: 1, description: "Gain +3 Power on move." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Gain +4 Power." },
    ],
  },
  {
    id: "tralalero_tralala",
    name: "Tralalero Tralala",
    slug: "tralalero-tralala",
    rarity: "Rare",
    cost: 3,
    power: 3,
    abilityText: "On Reveal: A random friendly +3 Power or random enemy -3 Power.",
    abilityType: "on_reveal",
    abilityId: "chaosBuffOrDebuff",
    tags: ["Chaos", "Brainrot", "On Reveal"],
    imagePath: "/cards/tralalero-tralala.png",
    flavor: "Three-legged shark in Nikes. Outcomes may vary.",
    levels: [
      { level: 1, description: "Random friendly +3 or enemy -3." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 3, abilityBonus: 1, description: "Effect magnitude raised to 4." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Magnitude 5." },
    ],
  },
  {
    id: "bombardino_crocodilo",
    name: "Bombardino Crocodilo",
    slug: "bombardino-crocodilo",
    rarity: "Epic",
    cost: 5,
    power: 7,
    abilityText: "On Reveal: Give all enemy cards here -1 Power.",
    abilityType: "on_reveal",
    abilityId: "debuffEnemiesHere",
    tags: ["AoE", "Brainrot", "On Reveal"],
    imagePath: "/cards/bombardino-crocodilo.png",
    flavor: "A crocodile. With bomber jets. Don't ask.",
    levels: [
      { level: 1, description: "All enemies here -1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 8)." },
      { level: 3, abilityBonus: 1, description: "Enemies here -2 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 9)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Enemies -3." },
    ],
  },
  {
    id: "wojak",
    name: "Wojak",
    slug: "wojak",
    rarity: "Common",
    cost: 1,
    power: 0,
    abilityText: "On Reveal: Give the next card you play +2 Power.",
    abilityType: "on_reveal",
    abilityId: "buffNextPlayed",
    tags: ["Support", "Buff", "On Reveal"],
    imagePath: "/cards/wojak.png",
    flavor: "It's over. (It's not. Your next card's juiced.)",
    levels: [
      { level: 1, description: "Next card you play +2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 1)." },
      { level: 3, abilityBonus: 1, description: "Next card +3 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 2)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Next card +4." },
    ],
  },
  {
    id: "sigma_cat",
    name: "Sigma Cat",
    slug: "sigma-cat",
    rarity: "Rare",
    cost: 2,
    power: 2,
    abilityText: "Ongoing: Your other cards here have +1 Power.",
    abilityType: "ongoing",
    abilityId: "ongoingBuffOthersHere",
    tags: ["Cat", "Ongoing", "Support"],
    imagePath: "/cards/sigma-cat.png",
    flavor: "Grindset incarnate. Lifts the whole lane, quietly.",
    levels: [
      { level: 1, description: "Other cards here +1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 3, abilityBonus: 1, description: "Other cards here +2 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Others +3." },
    ],
  },
  {
    id: "cappuccino_assassin",
    name: "Cappuccino Assassin",
    slug: "cappuccino-assassin",
    rarity: "Rare",
    cost: 4,
    power: 5,
    abilityText: "On Reveal: Destroy the lowest-Power enemy card here.",
    abilityType: "on_reveal",
    abilityId: "destroyLowestEnemyHere",
    tags: ["Execute", "Destroy", "On Reveal"],
    imagePath: "/cards/cappuccino-assassin.png",
    flavor: "Serves justice at exactly 65°C.",
    levels: [
      { level: 1, description: "Destroy lowest-Power enemy here." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 7)." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 8)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "rare_pepe",
    name: "Rare Pepe",
    slug: "rare-pepe",
    rarity: "Epic",
    cost: 4,
    power: 4,
    abilityText: "Ongoing: Your On Reveal cards here have +1 Power.",
    abilityType: "ongoing",
    abilityId: "ongoingBuffOnRevealHere",
    tags: ["Pepe", "Ongoing", "Support"],
    imagePath: "/cards/rare-pepe.png",
    flavor: "Worth more than your portfolio. Probably.",
    levels: [
      { level: 1, description: "Your On Reveal cards here +1." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 3, abilityBonus: 1, description: "On Reveal cards here +2." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. +3." },
    ],
  },
  {
    id: "bonk_dog",
    name: "Bonk Dog",
    slug: "bonk-dog",
    rarity: "Common",
    cost: 2,
    power: 4,
    abilityText: "No ability.",
    abilityType: "none",
    abilityId: null,
    tags: ["Simple", "Animal"],
    imagePath: "/cards/bonk-dog.png",
    flavor: "Bonk. Solid stats, zero drama.",
    levels: [
      { level: 1, description: "Vanilla 4 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 7)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "degen_trader",
    name: "Degen Trader",
    slug: "degen-trader",
    rarity: "Common",
    cost: 2,
    power: 1,
    abilityText: "On Reveal: Draw a card.",
    abilityType: "on_reveal",
    abilityId: "drawCard",
    tags: ["Draw", "On Reveal"],
    imagePath: "/cards/degen-trader.png",
    flavor: "One more trade. One more card. Just one more.",
    levels: [
      { level: 1, description: "Draw a card." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 2)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 4, abilityBonus: 1, description: "Draw 2 cards." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "whale",
    name: "Whale",
    slug: "whale",
    rarity: "Epic",
    cost: 5,
    power: 9,
    abilityText: "Ongoing: Enemy cards here with 2 or less Power have -1 Power.",
    abilityType: "ongoing",
    abilityId: "ongoingDebuffSmallEnemiesHere",
    tags: ["Whale", "Ongoing"],
    imagePath: "/cards/whale.png",
    flavor: "Moves the market by existing.",
    levels: [
      { level: 1, description: "Small enemies here -1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 10)." },
      { level: 3, abilityBonus: 1, description: "Affects 3-Power-or-less enemies." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 11)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "rug_pull_goblin",
    name: "Rug Pull Goblin",
    slug: "rug-pull-goblin",
    rarity: "Rare",
    cost: 3,
    power: 2,
    abilityText: "On Reveal: Move an enemy card here to a random other location.",
    abilityType: "on_reveal",
    abilityId: "moveEnemyCard",
    tags: ["Disrupt", "Move", "On Reveal"],
    imagePath: "/cards/rug-pull-goblin.png",
    flavor: "Wen lambo? Never. Wen rug? Now.",
    levels: [
      { level: 1, description: "Move an enemy card from here." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 4, abilityBonus: 1, description: "Move the strongest enemy here." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "market_maker",
    name: "Market Maker",
    slug: "market-maker",
    rarity: "Legendary",
    cost: 5,
    power: 6,
    abilityText: "End of game: Swap this card's Power with the strongest enemy here.",
    abilityType: "end_game",
    abilityId: "swapPowerEndGame",
    tags: ["Manipulation", "End Game"],
    imagePath: "/cards/market-maker.png",
    flavor: "Sets the price. You just pay it.",
    levels: [
      { level: 1, description: "Swap Power with strongest enemy here." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 7)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 8)." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 9)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "bot_minion",
    name: "Bot Minion",
    slug: "bot-minion",
    rarity: "Common",
    cost: 1,
    power: 1,
    abilityText: "No ability.",
    abilityType: "none",
    abilityId: null,
    tags: ["Token", "Bot"],
    imagePath: "/cards/bot-minion.png",
    flavor: "gm gm gm gm gm",
    levels: [
      { level: 1, description: "Vanilla 1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 2)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "liquidity_vampire",
    name: "Liquidity Vampire",
    slug: "liquidity-vampire",
    rarity: "Epic",
    cost: 4,
    power: 4,
    abilityText: "On Reveal: Steal 2 Power from the strongest enemy card here.",
    abilityType: "on_reveal",
    abilityId: "stealPower",
    tags: ["Drain", "On Reveal"],
    imagePath: "/cards/liquidity-vampire.png",
    flavor: "Drains the pool. Yours, specifically.",
    levels: [
      { level: 1, description: "Steal 2 Power from strongest enemy here." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 3, abilityBonus: 1, description: "Steal 3 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Steal 4." },
    ],
  },
  {
    id: "jeet_dragon",
    name: "Jeet Dragon",
    slug: "jeet-dragon",
    rarity: "Epic",
    cost: 4,
    power: 8,
    abilityText: "At the end of turn 5, this loses 3 Power.",
    abilityType: "conditional",
    abilityId: "losePowerAfterTurn5",
    tags: ["Tempo", "Conditional"],
    imagePath: "/cards/jeet-dragon.png",
    flavor: "Sells the top every time. Even its own.",
    levels: [
      { level: 1, description: "Loses 3 Power after turn 5." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 9)." },
      { level: 3, abilityBonus: 1, description: "Only loses 2 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 10)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Loses only 1." },
    ],
  },
  {
    id: "diamond_hands",
    name: "Diamond Hands",
    slug: "diamond-hands",
    rarity: "Rare",
    cost: 3,
    power: 3,
    abilityText: "Ongoing: Your cards here can't be moved.",
    abilityType: "ongoing",
    abilityId: "ongoingPreventMoveHere",
    tags: ["Defense", "Ongoing"],
    imagePath: "/cards/diamond-hands.png",
    flavor: "💎🙌 Never selling. Never moving.",
    levels: [
      { level: 1, description: "Your cards here can't be moved." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 3, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 6)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "hype_man",
    name: "Hype Man",
    slug: "hype-man",
    rarity: "Rare",
    cost: 2,
    power: 2,
    abilityText: "On Reveal: Give a card in your hand +2 Power.",
    abilityType: "on_reveal",
    abilityId: "buffHandCard",
    tags: ["Buff", "On Reveal"],
    imagePath: "/cards/hype-man.png",
    flavor: "WAGMI! WAGMI! WAGMI!",
    levels: [
      { level: 1, description: "A card in hand +2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 3, abilityBonus: 1, description: "Hand card +3 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Hand card +4." },
    ],
  },
  {
    id: "trenches_rat",
    name: "Trenches Rat",
    slug: "trenches-rat",
    rarity: "Common",
    cost: 1,
    power: 3,
    abilityText: "If played after turn 3, this has -2 Power.",
    abilityType: "conditional",
    abilityId: "penaltyIfLate",
    tags: ["Early", "Conditional"],
    imagePath: "/cards/trenches-rat.png",
    flavor: "First in the trenches. Useless once it's safe.",
    levels: [
      { level: 1, description: "After turn 3, -2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 4)." },
      { level: 3, abilityBonus: 1, description: "Penalty reduced to -1." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 5)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. No penalty." },
    ],
  },
  {
    id: "pump_candle",
    name: "Pump Candle",
    slug: "pump-candle",
    rarity: "Rare",
    cost: 3,
    power: 1,
    abilityText: "At the end of each turn, this gains +1 Power.",
    abilityType: "ongoing",
    abilityId: "gainPerTurn",
    tags: ["Scaling", "Ongoing"],
    imagePath: "/cards/pump-candle.png",
    flavor: "Green candle. Green candle. GREEN CANDLE.",
    levels: [
      { level: 1, description: "+1 Power each turn end." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 2)." },
      { level: 3, abilityBonus: 1, description: "+2 Power each turn end." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. +2/turn." },
    ],
  },
  {
    id: "bear_market",
    name: "Bear Market",
    slug: "bear-market",
    rarity: "Epic",
    cost: 4,
    power: 6,
    abilityText: "Ongoing: Enemy cards here have -1 Power.",
    abilityType: "ongoing",
    abilityId: "ongoingDebuffEnemiesHere",
    tags: ["Ongoing", "Debuff"],
    imagePath: "/cards/bear-market.png",
    flavor: "It's so over. (For them.)",
    levels: [
      { level: 1, description: "Enemy cards here -1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 7)." },
      { level: 3, abilityBonus: 1, description: "Enemy cards here -2 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 8)." },
      { level: 5, powerBonus: 1, description: "Premium frame. +1 base Power." },
    ],
  },
  {
    id: "bull_run",
    name: "Bull Run",
    slug: "bull-run",
    rarity: "Legendary",
    cost: 5,
    power: 8,
    abilityText: "On Reveal: Give your other cards here +2 Power.",
    abilityType: "on_reveal",
    abilityId: "buffOthersHere",
    tags: ["Buff", "On Reveal"],
    imagePath: "/cards/bull-run.png",
    flavor: "We're so back. We were never not back.",
    levels: [
      { level: 1, powerBonus: 0, abilityBonus: 1, description: "Other cards here +2 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 9)." },
      { level: 3, abilityBonus: 1, description: "Other cards here +3 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 10)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Others +4." },
    ],
  },
  {
    id: "alpha_caller",
    name: "Alpha Caller",
    slug: "alpha-caller",
    rarity: "Common",
    cost: 1,
    power: 1,
    abilityText: "On Reveal: Give the leftmost card in your hand +1 Power.",
    abilityType: "on_reveal",
    abilityId: "buffLeftmostHand",
    tags: ["Buff", "On Reveal"],
    imagePath: "/cards/alpha-caller.png",
    flavor: "Trust me bro, this one's different.",
    levels: [
      { level: 1, description: "Leftmost hand card +1 Power." },
      { level: 2, powerBonus: 1, description: "+1 base Power (Power 2)." },
      { level: 3, abilityBonus: 1, description: "Leftmost hand card +2 Power." },
      { level: 4, powerBonus: 1, description: "+1 base Power (Power 3)." },
      { level: 5, abilityBonus: 1, description: "Premium frame. Leftmost +3." },
    ],
  },
];

/* ---- Engine-only token definitions (not in player pools) ---- */
export const SNAP_TOKENS: Record<string, SnapCardDef> = {
  pop_token: {
    id: "pop_token",
    name: "Pop Token",
    slug: "pop-token",
    rarity: "Common",
    cost: 0,
    power: 1,
    abilityText: "No ability.",
    abilityType: "none",
    abilityId: null,
    tags: ["Token"],
    imagePath: "/cards/popcat.png",
    flavor: "Pop.",
    levels: [{ level: 1, description: "1 Power token." }],
    isToken: true,
  },
  meme_token: {
    id: "meme_token",
    name: "Meme Token",
    slug: "meme-token",
    rarity: "Common",
    cost: 0,
    power: 1,
    abilityText: "No ability.",
    abilityType: "none",
    abilityId: null,
    tags: ["Token"],
    imagePath: "/cards/bonk-dog.png",
    flavor: "Pure, distilled hopium.",
    levels: [{ level: 1, description: "1 Power token." }],
    isToken: true,
  },
  bot_token: {
    id: "bot_token",
    name: "Bot",
    slug: "bot-token",
    rarity: "Common",
    cost: 0,
    power: 1,
    abilityText: "No ability.",
    abilityType: "none",
    abilityId: null,
    tags: ["Token", "Bot"],
    imagePath: "/cards/bot-minion.png",
    flavor: "beep boop wagmi",
    levels: [{ level: 1, description: "1 Power token." }],
    isToken: true,
  },
};

export const SNAP_CARDS_BY_ID: Record<string, SnapCardDef> = Object.fromEntries(
  SNAP_CARDS.map((c) => [c.id, c]),
);

/** Lookup that also resolves engine tokens. */
export function getSnapCardDef(id: string): SnapCardDef | undefined {
  return SNAP_CARDS_BY_ID[id] ?? SNAP_TOKENS[id];
}

/** Base power for a card at a given level (level upgrades stack additively). */
export function snapCardPowerAtLevel(def: SnapCardDef, level: number): number {
  let p = def.power;
  for (const lv of def.levels) {
    if (lv.level <= level) p += lv.powerBonus ?? 0;
  }
  return p;
}

/** Cost for a card at a given level. */
export function snapCardCostAtLevel(def: SnapCardDef, level: number): number {
  let c = def.cost;
  for (const lv of def.levels) {
    if (lv.level <= level) c -= lv.costReduction ?? 0;
  }
  return Math.max(0, c);
}

/** Cumulative ability bonus from levels (interpreted per-ability handler). */
export function snapCardAbilityBonusAtLevel(def: SnapCardDef, level: number): number {
  let b = 0;
  for (const lv of def.levels) {
    if (lv.level <= level) b += lv.abilityBonus ?? 0;
  }
  return b;
}

/** The 12-card SNAP starter deck. */
export const SNAP_STARTER_DECK_IDS: string[] = [
  "popcat",
  "alpha_caller",
  "peanut_the_squirrel",
  "wojak",
  "dogwifhat",
  "sigma_cat",
  "hype_man",
  "pepe_the_frog",
  "mog_cat",
  "cappuccino_assassin",
  "bear_market",
  "gigachad",
];

export const SNAP_DECK_SIZE = 12;
